language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - doxygen

env:
  CXX=g++-7

script:
  - mkdir build
  - cd build
  - cmake ..
  - make build_tests
  - make test

notifications:
  email: false
