language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - doxygen

env:
  COMPILER=g++-7

before_install:
  - eval "${COMPILER}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make build_tests
  - make test

notifications:
  email: false
